### ISSUE TITLE
--english option is generating an error

### ISSUE THREAD

**Issue by SunnyOd** [mallorbc/whisper_mic#1]
Great work, Blake. This has helped me no-end getting off of google docs voice typing.

Got one issue. Specifying `--english` generates the following error:

```
Traceback (most recent call last):
  File "/home/sunny/Developer/whisper_mic/mic.py", line 48, in <module>
    main()
  File "/home/sunny/.conda/envs/whisper/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sunny/.conda/envs/whisper/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sunny/.conda/envs/whisper/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sunny/.conda/envs/whisper/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sunny/Developer/whisper_mic/mic.py", line 42, in main
    result = audio_model.transcribe(save_path)
  File "/home/sunny/.conda/envs/whisper/lib/python3.9/site-packages/whisper/transcribe.py", line 82, in transcribe
    _, probs = model.detect_language(segment)
  File "/home/sunny/.conda/envs/whisper/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sunny/.conda/envs/whisper/lib/python3.9/site-packages/whisper/decoding.py", line 35, in detect_language
    raise ValueError(f"This model doesn't have language tokens so it can't perform lang id")
ValueError: This model doesn't have language tokens so it can't perform lang id
```

Works fine without this flag

**Comment by mallorbc** [comment]
I think this is fixed with #3
