### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by MohammadAboulEla** [mallorbc/whisper_mic#70]
[02/27/24 18:25:02] INFO     No mic index provided, using     whisper_mic.py:84
                             default                                           
Traceback (most recent call last):
  File "D:\programing\Python\LearnAI\mic_to_text.py", line 3, in <module>
    mic = WhisperMic()
          ^^^^^^^^^^^^
  File "D:\programing\Python\LearnAI\.venv\Lib\site-packages\whisper_mic\whisper_mic.py", line 79, in __init__
    self.__setup_mic(mic_index)
  File "D:\programing\Python\LearnAI\.venv\Lib\site-packages\whisper_mic\whisper_mic.py", line 85, in __setup_mic
    self.source = sr.Microphone(sample_rate=16000, device_index=mic_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programing\Python\LearnAI\.venv\Lib\site-packages\speech_recognition\__init__.py", line 80, in __init__
    self.pyaudio_module = self.get_pyaudio()
                          ^^^^^^^^^^^^^^^^^^
  File "D:\programing\Python\LearnAI\.venv\Lib\site-packages\speech_recognition\__init__.py", line 111, in get_pyaudio
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

[EDIT] fixed with
pip install setuptools

**Comment by MohammadAboulEla** [comment]
fixed with
pip install setuptools
